### ISSUE TITLE
Hang when clicking the HTTPS shield

### ISSUE THREAD

**Issue by cassidyjames** [alcinnz/Odysseus#163]
The entire browser hangs when trying to show more info. Reproduced on elementary.io, google.com, duckduckgo.com and every other site I tried.

**Comment by alcinnz** [comment]
I see it now, will debug.

**Comment by alcinnz** [comment]
Turns out something was broken with the code for showing the certificate chain. I don't know what, but I've disabled it to fix the freeze and will open a new issue to at the very least understand why it's broken.

Now I only show the site's own certificate, not that of any of it's issuers. Can't say I've seen any of those in practice before.

**Comment by alcinnz** [comment]
Remaining issue tracked in #165
