### ISSUE TITLE
Won't start in Manjaro Gnome

### ISSUE THREAD

**Issue by tiotrom** [alcinnz/Odysseus#198]
Here's the error:
```
ERROR:src/com.github.alcinnz.odysseus.p/Services/Prosody/slice.c:244:_vala_g_bytes_get: assertion failed: (index >= 0 && index < (int) this.get_size ())
Bail out! ERROR:src/com.github.alcinnz.odysseus.p/Services/Prosody/slice.c:244:_vala_g_bytes_get: assertion failed: (index >= 0 && index < (int) this.get_size ())
Aborted (core dumped)

```

**Comment by alcinnz** [comment]
I'll make sure to investigate this week!

**Comment by tiotrom** [comment]
Any updates?
```

**
ERROR:src/com.github.alcinnz.odysseus.p/Services/Prosody/slice.c:244:_vala_g_bytes_get: assertion failed: (index >= 0 && index < (int) this.get_size ())
Bail out! ERROR:src/com.github.alcinnz.odysseus.p/Services/Prosody/slice.c:244:_vala_g_bytes_get: assertion failed: (index >= 0 && index < (int) this.get_size ())
Aborted (core dumped)
```

**Comment by alcinnz** [comment]
Sorry, no. I was juggling other projects and work.

I'm now turning my focus towards Odysseus and should *hopefully* have this fixed tomorrow.

**Comment by alcinnz** [comment]
Sorry it took me so long! The issue is now solved in master, and I'll release an update to AUR shortly.

Mostly the delay was in setting up a fresh test VM, but once I did I found it was erroring out upon buffer overflow when parsing internal templates. I thought I had caught that error, but now I'm handling it in a wrapper class I originally put in for performance reasons.

Please reopen if you still face issues after the update!
