### ISSUE TITLE
elementary app store links broken

### ISSUE THREAD

**Issue by zvirdaniel** [alcinnz/Odysseus#56]
When clicking on "Home page" or "Submit bugs" in the AppStore listing, it directs me to GitHub pages, rather than this site, or your other project sites. And since you named the project Odysseus, searching it with combination of "elementary" gives me results about greek mythology in elementary schoolds, rather than this project.

**Comment by alcinnz** [comment]
Ah, yes. I confirmed the problem. And I see what is wrong with the link.

Fix coming soon.

**Comment by alcinnz** [comment]
Fix committed. Will be live in the elementary AppCenter in a day or so.

**Comment by alcinnz** [comment]
I just checked Odysseus's searchability. It does have some issues, I agree, but it does come to the top of the results when your search "elementary os odysseus" or "odysseus web browser", on both Google and DuckDuckGo.

Otherwise I don't know what to do about it's searchability short of a name change.
