### ISSUE TITLE
Blurry fonts

### ISSUE THREAD

**Issue by giovannicaligaris** [alcinnz/Odysseus#61]
This only happens on Google+, I have the same issue on Epiphany.

I'm not sure if this is a WebKit issue.

![screenshot from 2018-01-02 07 43 31](https://user-images.githubusercontent.com/26255347/34477299-f5b58484-ef90-11e7-9d27-52bdaa4f1a72.png)

**Comment by alcinnz** [comment]
Well, if it's shared with Epiphany (and not necessarily other browsers) this is probably a bug in the GTK port of WebKit. Especially since it's to do with fonts on the Web, as that falls squarly within it's dominion. 

I could also add a workaround to disable the fonts used by plus.google.com, but it strikes me as more time effective to allow others to make these sort of fixes themselves using [userstyles](https://userstyles.org/). And I could promote the CSS fixes for problems as surfers experience them.

---

To fix the root problem though, you could [report the issue](https://bugs.webkit.org/enter_bug.cgi) to WebKitGTK (be sure to mark it WebKitGTK specific, as Safari probably doesn't have this issue), or I am happy to do so on your behalf. However you may be able to provide more detail. 

I'll report this bug upstream in 24 hours, and if you do report the issue to WebKitGTK in the meantime please link to it here so I can help out.

**Comment by alcinnz** [comment]
#63

**Comment by alcinnz** [comment]
I've just added a bandaid.

**Comment by alcinnz** [comment]
Oooh, it turns out it's Google at fault here and the issue would span **all** WebKit-based browsers including Safari.

The thing is Google told WebKit to use a lesser algorithm for rendering the text. They should really read [Please Stop "Fixing" Font Smoothing](http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/).

I'm swapping out a better bandaid now.

**Comment by alcinnz** [comment]
Now I've generalized Google+'s style fix to all websites. Web developers can no longer make the mistake of asking Odysseus for blurry or jagged text.

**Comment by giovannicaligaris** [comment]
@alcinnz, thank you for taking your time and solving this issue. Now I can finally ditch Epiphany.

I'll wait until 1.0.13 is realased in the Appcenter so I can test it out.

Thank you!!!

**Comment by giovannicaligaris** [comment]
Tested. Looks much better now!
