### ISSUE TITLE
Midori source code

### ISSUE THREAD

**Issue by giovannicaligaris** [alcinnz/Odysseus#71]
Back in the day I used to be a big fan of Midori but it has been discontinued for a few years now. 

I was wondering if it is possible to use some or most of Midori lines of codes and intergrate it with Odysseus?

http://midori-browser.org/

**Comment by alcinnz** [comment]
Same here, it's a shame that they didn't make the update to WebKit2. 

Without that they failed to gain important security and performance improvements, as well as any HTML5 support that's been added since then.

However the new APIs are significantly different which is the reason for the failed upgrade, so while it would be useful to refer to that code it's almost as easy to write it from scratch.

**Comment by alcinnz** [comment]
Are wanting bookmarks & history? Me too. 

I've been working on history [here](https://github.com/alcinnz/Odysseus/tree/feature/history%2Bdefault), and from there most additional browser features would be just a small step. 

It's not far from completion, I just need to find the time to do so.

**Comment by alcinnz** [comment]
Tested it now, and it's segfaulting when I try to view the browser history. So I'll release some of the fixes for other issues today and debug this over the next few days.

---

On the technical side, what I know so far is that this will probably consist of two fixes. That's because I've (re)developed a high-level DSL (domain specific language, like HTML, CSS, & SQL) to help with implementing periphery UI components, and I've used it to develop the history viewer. So the first thing to fix is for that DSL to give a more helpful error message rather than crashing the browser, simply to make these issues easier to fix next time. But second since this is the first time in a long time that said DSL is crashing (which I've been monitoring well), there's probably something wrong with the history viewer which also needs fixing.

**Comment by alcinnz** [comment]
I've answered your question, and I've now created seperate issues for the basic browser features I've still got to implement. I'll keep you updated on those other issues where I can be more finegrained.

For the both these reasons, I'll close this issue.

**Comment by alcinnz** [comment]
On those other issues I've detailed my UI (and technical) plans, so if you want you can give me feedback on those UI concepts.

**Comment by alcinnz** [comment]
Ah just looked at their code and was pleasently surprised to see they've made the upgrade! So now maybe I could incorporate some of their code as-needed.

The main thing seperating us now is how we want to present our extended UIs. They ofcourse use a sidepanel containing treeviews whilst I've just prepared to render (most of them) as webpages. It's really quite superficial, but I hope my approach will reduce perceived complexity, open up new design possibilities, and keep my code cleaner.

But mostly seeing Midori's code just reiterated how vital the database infrastructure I've been doing is to fully functioning browser.

**Comment by giovannicaligaris** [comment]
That is good news. I hope this would help speed up development. 

Thank you for all of your hard work.

**Comment by giovannicaligaris** [comment]
Midori is being developed again, I just checked their website.
