### ISSUE TITLE
Application not launch on eOS Juno

### ISSUE THREAD

**Issue by btd1337** [alcinnz/Odysseus#96]
`[INFO 13:21:39.410694] Application.vala:154: Odysseus version: 1
[INFO 13:21:39.410751] Application.vala:156: Kernel version: 4.15.0-13-generic2
[ERROR 13:21:39.478262] database.vala:34: Failed to execute SQL: not authorized: -- Must be loaded for each process.SELECT load_extension('/usr/share/Odysseus/libfts5.so');
[1]    2009 trace trap (core dumped)  com.github.alcinnz.odysseus %U`

![captura de tela de 2018-05-25 13 22 32](https://user-images.githubusercontent.com/11943860/40555256-dbea4676-601e-11e8-8784-445483985ac0.png)

**Comment by alcinnz** [comment]
What I can say right-off is that this code is there in order to initialize the search infrastructure for the history viewer. What I'm doing is loading an SQLite extension I bundled with Odysseus after failing to find it in the OS repositories (and besides, it'd be nice to make a very minor edit to the search syntax).

I don't know what the "not authorized" is about though, does `/usr/share/Odysseus/libfts5.so` exist?

**Comment by alcinnz** [comment]
If it does, I know how to discuss what might've changed with elementary to cause this error. And it's worth saying it looks about as easy to fix this error as it would be too suppress it as the latter would require an entirely new code-path.

Oh, and thanks for reporting this. I very much want to support Juno!

**Comment by btd1337** [comment]
@alcinnz Yes, /usr/share/Odysseus/libfts5.so exists.

**Comment by alcinnz** [comment]
Thanks, I'll ask elementary what might've changed in Juno to cause this.

**Comment by alcinnz** [comment]
Sorry it's taking me so long to get this fixed. I've gotten answers from elementary on what could be wrong. And I don't know how to get access to Juno so I can diagnose the problem myself.

I'm seeing what I can do now.

**Comment by alcinnz** [comment]
Looking at the SQLite documentation, at first it seemed that this was a really weird to occur. Because according to that documentation you need to configure an authorization callback for it to have any meaning, and I am not doing that.

But then I found documentation saying that `load_extension` is disabled by default in recent versions of SQLite in which case the authorization error makes sense.

The API for enabling this function is not available in Freya, and nor am I finding the API to load the extension in via Vala.

Maybe there's a way for me to statically link it in.

**Comment by alcinnz** [comment]
I think I'll try something tomorrow but you'll have to tell me if it works.

**Comment by alcinnz** [comment]
Got through the difficult part of switching over to some code I think should work on both Freya & Juno. If all goes well, I'll be asking you to test this for me.

**Comment by alcinnz** [comment]
All isn't going well. First I had a segfault doing it one way, and it fails to compile (at the linking stage) another way.

**Comment by alcinnz** [comment]
Juno's beta's out! So I can debug this better myself!

**Comment by alcinnz** [comment]
Failed to do a quick fix on Juno, and my previous attempted fail entirely there too.

**Comment by alcinnz** [comment]
I keep running into dead ends! I'm failing to statically link SQLite's FullTextSearch extension in as a library, Juno's version doesn't want me to load it via the SQL function (for understandable security reasons) but as far as I can tell the Vala bindings don't provide the replacement functions or a means to reenable that syntax.

I'd really like some help (which I've asked for but haven't received), and I don't know if I can cleanly run without that SQL extension. Still I'll try to push through.

**Comment by alcinnz** [comment]
Woooah! History search *does* work out of the box without me needing to go through any of the pain I was attempting!

The SQLite plugin I needed appears to be preenabled in Juno.
